import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class PanelSwitcherController implements ActionListener {

	/** 
	 * The model of the MVC implementation of the PaintSwitcher
	 * */
	private PanelSwitcherModel model;
	
	/** 
	 * The view of the MVC implementation of the PaintSwitcher
	 * */	
	private PanelSwitcherView view;
	
	/**
	 * This saves the model and and view.
	 * 
	 * @param model a PanelSwitcherModel for storing the state of the currently
	 * displayed panel.
	 * @param view a PanelSwitcherView for what should be displayed in the GUI
	 */
	public PanelSwitcherController(PanelSwitcherModel model, 
			PanelSwitcherView view) {
		this.model = model;
		this.view = view;
	}

	/**
	 * Determines what to do with the event generated by the GUI.
	 * The event will only trigger a change when an event is passed from 
	 * the button with text "Switch Panels".
	 *  
	 * @param e an event from the GUI
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		String command = e.getActionCommand();
		if(command.equals("Switch Panels")){
			model.switchPanel();
			view.displayPanel(model.whichPanel());
		}
	}
}
